[package]
name = "highflowey/uicomponents"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["test", "Packages", "node_modules", "lib", "build"]

[dependencies]
fusion = "elttob/fusion@0.2.0"